### ISSUE TITLE
division command that divides [var1] by [var2] and sets it to [var1]

### ISSUE THREAD

**Issue by madeforlosers** [TaserTheFox/EsoFur-Interpreter#23]
Like how Baps divides [var2] by [var1], I suggest a command that divides [var1] by [var2].

Edited by Taser for future reference:
division command that divides [var1] by [var2] and sets it to [var1], aka reverse current command and assign it.

**Comment by TaserTheFox** [comment]
so is this just the division command, but reversed?

**Comment by TaserTheFox** [comment]
hmm... I mean, the division command I think is good as is, but maybe I'll add it later down the line, if that even is going to be a thing.  Thank you for the suggestion though. Gonna close this as not planned, but feel free to add more comments.
